name: Build FalconEngine

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Dependencies
        shell: pwsh
        run: |
          # Create a local registry to bypass the 128 Git error
          $repoRoot = "${{ github.workspace }}"
          
          # Force vcpkg to use its own internal baseline instead of a remote one
          & "$env:VCPKG_INSTALLATION_ROOT/vcpkg.exe" install `
            --x-manifest-root="$repoRoot" `
            --vcpkg-root="$env:VCPKG_INSTALLATION_ROOT" `
            --triplet x64-windows-static-md

      - name: Build with CMake
        shell: pwsh
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static-md `
            -DVCPKG_MANIFEST_MODE=ON
          
          cmake --build build --config Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: FalconEngine-Plugin
          path: "**/build/Release/FalconEngine.dll"
